CREATE TABLE IF NOT EXISTS UM_USER (
  UM_ID INTEGER NOT NULL AUTO_INCREMENT,
  UM_USER_NAME VARCHAR(255) NOT NULL,
  UM_USER_PASSWORD VARCHAR(512) NOT NULL,
  UM_CHANGED_TIME TIMESTAMP NOT NULL,
  PRIMARY KEY (UM_ID),
UNIQUE(UM_USER_NAME));

CREATE TABLE IF NOT EXISTS UM_USER_ATTRIBUTE (
  UM_ID INTEGER NOT NULL AUTO_INCREMENT,
  UM_ATTR_NAME VARCHAR(255) NOT NULL,
  UM_ATTR_VALUE VARCHAR(1024),
  UM_USER_ID INTEGER,
  PRIMARY KEY (UM_ID),
  FOREIGN KEY (UM_USER_ID) REFERENCES UM_USER(UM_ID));

CREATE INDEX IF NOT EXISTS UM_USER_ID_INDEX ON UM_USER_ATTRIBUTE(UM_USER_ID);

CREATE TABLE IF NOT EXISTS UM_SYSTEM_ROLE(
  UM_ID INTEGER NOT NULL AUTO_INCREMENT,
  UM_ROLE_NAME VARCHAR(255),
  PRIMARY KEY (UM_ID)
);

CREATE TABLE IF NOT EXISTS UM_SYSTEM_USER_ROLE(
  UM_ID INTEGER NOT NULL AUTO_INCREMENT,
  UM_USER_NAME VARCHAR(255),
  UM_ROLE_ID INTEGER NOT NULL,
  UNIQUE (UM_USER_NAME, UM_ROLE_ID),
  FOREIGN KEY (UM_ROLE_ID) REFERENCES UM_SYSTEM_ROLE(UM_ID),
  PRIMARY KEY (UM_ID)
);

