CREATE TABLE IF NOT EXISTS SM_SWITCH (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  OWNER VARCHAR(255) NOT NULL,
  DPID VARCHAR(50) NOT NULL,
  CREATED_TIME TIMESTAMP NOT NULL,
  LAST_UPDATED_TIME TIMESTAMP NOT NULL,
  QUOTA INTEGER(8) DEFAULT 0,
  BILLING_DAY INTEGER,
  BILLING_DATE TIMESTAMP,
  STATUS VARCHAR(255) NOT NULL,
  UNIQUE (DPID),
  PRIMARY KEY (ID),
UNIQUE(DPID));

CREATE INDEX IF NOT EXISTS SM_SWITCH_ID_INDEX ON SM_SWITCH(OWNER);

CREATE TABLE IF NOT EXISTS SM_GROUP (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  GROUP_NAME VARCHAR(100) NOT NULL,
  SWITCH_ID INTEGER NOT NULL,
  CREATED_TIME TIMESTAMP NOT NULL,
  LAST_UPDATED_TIME TIMESTAMP NOT NULL,
  QUOTA_APP BOOLEAN NOT NULL DEFAULT FALSE,
  PARENTAL_APP BOOLEAN NOT NULL DEFAULT FALSE,
  IOT_SECURITY_APP BOOLEAN NOT NULL DEFAULT FALSE,
  QUOTA INTEGER(8) DEFAULT 0,
  UNIQUE (GROUP_NAME, SWITCH_ID),
  FOREIGN KEY (SWITCH_ID) REFERENCES SM_SWITCH(ID),
  PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS SM_GROUP_ID_INDEX ON SM_GROUP(SWITCH_ID);

CREATE TABLE IF NOT EXISTS SM_DEVICE (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  MAC_ADDRESS VARCHAR(50) NOT NULL,
  DEVICE_NAME VARCHAR(100) NOT NULL,
  CREATED_TIME TIMESTAMP NOT NULL,
  LAST_UPDATED_TIME TIMESTAMP NOT NULL,
  SWITCH_ID INTEGER NOT NULL,
  STATUS VARCHAR(50),
  GROUP_ID INTEGER,
  PROPERTY TEXT,
  UNIQUE (MAC_ADDRESS, SWITCH_ID),
  FOREIGN KEY (SWITCH_ID) REFERENCES SM_SWITCH(ID),
  PRIMARY KEY (ID));

