CREATE TABLE IF NOT EXISTS SM_SWITCH (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  UM_USER_NAME VARCHAR(255) NOT NULL,
  DPID VARCHAR(50) NOT NULL,
  CREATED_TIME TIMESTAMP NOT NULL,
  LAST_UPDATED_TIME TIMESTAMP NOT NULL,
  TOTAL_QUOTA INTEGER DEFAULT 0,
  BILLING_DAY INTEGER NOT NULL,
  BILLING_DATE TIMESTAMP NOT NULL,
  UNIQUE (DPID),
  PRIMARY KEY (ID),
UNIQUE(DPID));

CREATE INDEX IF NOT EXISTS SM_SWITCH_ID_INDEX ON SM_SWITCH(DPID);

CREATE TABLE IF NOT EXISTS SM_GROUP (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  GROUP_NAME VARCHAR(100) NOT NULL,
  SWITCH_DPID VARCHAR(50) NOT NULL,
  UM_USER_NAME VARCHAR(255) NOT NULL,
  CREATED_TIME TIMESTAMP NOT NULL,
  LAST_UPDATED_TIME TIMESTAMP NOT NULL,
  QUOTA_APP BOOLEAN NOT NULL DEFAULT FALSE,
  PARENTAL_APP BOOLEAN NOT NULL DEFAULT FALSE,
  IOT_SECURITY_APP BOOLEAN NOT NULL DEFAULT FALSE,
  MAX_QUOTA INTEGER DEFAULT 0,
  UNIQUE (GROUP_NAME, UM_USER_NAME, SWITCH_DPID),
  FOREIGN KEY (SWITCH_DPID) REFERENCES SM_SWITCH(DPID),
  PRIMARY KEY (ID),
UNIQUE(DPID));

CREATE INDEX IF NOT EXISTS SM_GROUP_ID_INDEX ON SM_GROUP(UM_USER_NAME);

CREATE TABLE IF NOT EXISTS SM_DEVICE (
  ID INTEGER NOT NULL AUTO_INCREMENT,
  MAC_ADDRESS VARCHAR(50) NOT NULL,
  DEVICE_NAME VARCHAR(100) NOT NULL,
  CREATED_TIME TIMESTAMP NOT NULL,
  LAST_UPDATED_TIME TIMESTAMP NOT NULL,
  SWITCH_DPID VARCHAR(50) NOT NULL,
  STATUS VARCHAR(50),
  BILLING_DATE TIMESTAMP NOT NULL,
  SM_GROUP_ID INTEGER,
  UNIQUE (MAC_ADDRESS, DPID),
  FOREIGN KEY (SWITCH_DPID) REFERENCES SM_SWITCH(DPID),
  FOREIGN KEY (SM_GROUP_ID) REFERENCES SM_GROUP(ID),
  PRIMARY KEY (ID),
UNIQUE(DPID));

CREATE INDEX IF NOT EXISTS SM_DEVICE_ID_INDEX ON SM_DEVICE(MAC_ADDRESS, DPID);
