CREATE TABLE IF NOT EXISTS PARENTAL_RECORDS (
     ID INTEGER auto_increment NOT NULL,
     DNS_DOMAIN VARCHAR(256) DEFAULT NULL,
     DEVICE_MAC VARCHAR(20) DEFAULT NULL,
     SWITCH_MAC VARCHAR(20) DEFAULT NULL,
     CREATED_TIMESTAMP TIMESTAMP NOT NULL,
     PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PARENTAL_TAG_RECORDS (
     DNS_DOMAIN VARCHAR(256) NOT NULL,
     TAGS VARCHAR(400) NOT NULL
     PRIMARY KEY (DNS_DOMAIN)
);
