CREATE TABLE IF NOT EXISTS PARENTAL_RECORDS (
     ID                    INTEGER AUTO_INCREMENT NOT NULL,
     DNS_DOMAIN VARCHAR(256) DEFAULT NULL,
     DEVICE_MAC VARCHAR(20) DEFAULT NULL,
     SWITCH_MAC VARCHAR(20) DEFAULT NULL,
     CREATED_TIMESTAMP TIMESTAMP NOT NULL,
     PRIMARY KEY (ID)
)ENGINE = InnoDB;

CREATE INDEX IDX_PARENTAL_RECORDS ON PARENTAL_RECORDS(SWITCH_MAC, DEVICE_MAC,DNS_DOMAIN);


CREATE TABLE IF NOT EXISTS PARENTAL_TAG_RECORDS (
     DNS_DOMAIN VARCHAR(256) NOT NULL,
     TAGS VARCHAR(400) NOT NULL
     PRIMARY KEY (DNS_DOMAIN)
)ENGINE = InnoDB;



